AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create an S3 bucket

Parameters:
#S3 Parameters  
  EnvType:
    Type: String
    Default: "dev"
    Description: 'The environment type (e.g., prod, dev)'
  DomainName:
    Type: String
    Description: 'The name of the domain'
  BucketFilePath:
    Type: String
    Description: 'bucket yaml path'

#LF Parameters    
  LFServiceRoleArn:
    Type: String
    Description: 'Lake Formation Register Location Service Role ARN'
    Default: "arn:aws:iam::903432419063:role/datamesh-stack-IAMRoles-R-LFRegisterLocationService-Q7UNtXXEF4XK"
#IAMRole Parameters
  IAMRolePath:
    Type: String
    Description: 'IAM Role yaml path'

#ResourceLink Parameters
  GovernanceAccountId:
    Type: String
    Description: 'Governance Account ID'
    Default: "903432419063"
  GovernanceDatabaseName:
    Type: String
    Description: 'Governance Database Name'
    Default: "sandbox---db"    
  ResourcelinkPath:
    Type: String
    Description: 'Resource Link yaml path Parameters'

#LF Parameters
  CodeBuildRole:
    Type: String
    Description: 'Code Build Role Which is used to build all CF reosurces'
    Default: "codebuild-sandbox-producer-service-role"
  lfPath:
    Type: String
    Description: 'LakeFormation yaml path Parameters' 
  lfpermissionsPath:
    Type: String
    Description: 'LakeFormation Permissions yaml path Parameters'         
#Glue Crawler Parameters
  # GlueCrawlerPath:
  #   Type: String
  #   Description: 'Crawler yaml path Parameters'       

Resources:
  s3buckets:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref BucketFilePath
      Parameters:
        EnvType: !Ref EnvType
        DomainName: !Ref DomainName
        LFServiceRoleArn: !Ref LFServiceRoleArn

  IAMRoles:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref IAMRolePath
      Parameters:
        EnvType: !Ref EnvType
        DomainName: !Ref DomainName

  GlueDBResourceLink:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref ResourcelinkPath
      Parameters:
        GovernanceAccountId: !Ref GovernanceAccountId
        GovernanceDatabaseName: !Ref GovernanceDatabaseName

  LakeFormationStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: s3buckets
    DependsOn: IAMRoles
    Properties:
      TemplateURL: !Ref lfPath
      Parameters:
        # DataLakeBucketName: !GetAtt s3buckets.Outputs.TrustedBucketName
        CodeBuildRole: !Ref CodeBuildRole
        # GlueCrawlerRoleArn: !GetAtt IAMRoles.Outputs.GlueCrawlerRoleArn
        # GovernanceAccountId: !Ref GovernanceAccountId

  # GlueCrawler:
  #   Type: AWS::CloudFormation::Stack
  #   DependsOn: IAMRoles
  #   DependsOn: LakeFormationStack    
  #   Properties:
  #     TemplateURL: !Ref GlueCrawlerPath
  #     Parameters:
  #       EnvType: !Ref EnvType
  #       DomainName: !Ref DomainName
  #       DatabaseName: !GetAtt GlueDBResourceLink.Outputs.ResourceLink
  #       S3Target: !GetAtt s3buckets.Outputs.TrustedBucketName
  #       GlueCrawlerRoleArn: !GetAtt IAMRoles.Outputs.GlueCrawlerRoleArn
  #       GovernanceAccountId: !Ref GovernanceAccountId

  LFPermissions:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref lfpermissionsPath
      Parameters:
        DatabaseName: !Ref GovernanceDatabaseName
        GlueDBResourceLink: !GetAtt GlueDBResourceLink.Outputs.ResourceLink
        GlueCrawlerRoleArn: !GetAtt IAMRoles.Outputs.GlueCrawlerRoleArn

Outputs:
  TrustedBucketName:
    Description: The name of the Landing S3 bucket
    Value: !GetAtt s3buckets.Outputs.TrustedBucketName

  GlueCrawlerRoleArn:
    Description: 'Glue Crawler IAM Role'
    Value: !GetAtt IAMRoles.Outputs.GlueCrawlerRoleArn
    Export:
      Name: GlueCrawlerRoleArn

  GlueDBResourceLink:
    Description: 'Resource Link of the shared Glue Database'
    Value: !GetAtt GlueDBResourceLink.Outputs.ResourceLink