version: 0.2
phases:
  build:
    commands:
      - |
        echo Build started on `date`
        filename="sample_config_file.txt"
        file=$CODEBUILD_SRC_DIR/config_files/"${filename}"
        echo $file
        echo Printing env variables
        echo "${env}"
        echo "${domain}"
        KEY="${domain}_${env}"
        echo "${KEY}"
        VALUE=$(grep "^${KEY}=" "$file" | sed -e "s/^${KEY}=//")
        if [ -z "$VALUE" ]; then
        echo "Key '$KEY' not found in $file"
        else echo "The value for '$KEY' is '$VALUE'"
        fi
        cfnfilename="main.yaml"
        cfnfile=$CODEBUILD_SRC_DIR/cfn/"${cfnfilename}"
        echo $cfnfile
        bucketfilename="bucket.yaml"
        bucketfile=$CODEBUILD_SRC_DIR/cfn/"${bucketfilename}"
        echo $bucketfile
        iamrolefilename="iam_roles.yaml"
        iamrolefile=$CODEBUILD_SRC_DIR/cfn/"${iamrolefilename}"
        echo $iamrolefile
        dbresourcelinkfilename="glue_resourcelink.yaml"
        dbresourcelinkfile=$CODEBUILD_SRC_DIR/cfn/"${dbresourcelinkfilename}"
        echo $dbresourcelinkfile
        lfpermissionsfilename="lfpermissions.yaml"
        lfpermissionsfile=$CODEBUILD_SRC_DIR/cfn/"${lfpermissionsfilename}"
        echo $lfpermissionsfile
        lffilename="lakeformation.yaml"
        lffile=$CODEBUILD_SRC_DIR/cfn/"${lffilename}"
        echo $lffile
        aws s3 cp $iamrolefile s3://mycicd-bucket-ap3/cicd-files/
        aws s3 cp $bucketfile s3://mycicd-bucket-ap3/cicd-files/
        aws s3 cp $dbresourcelinkfile s3://mycicd-bucket-ap3/cicd-files/
        aws s3 cp $lfpermissionsfile s3://mycicd-bucket-ap3/cicd-files/
        aws s3 cp $lffile s3://mycicd-bucket-ap3/cicd-files/                                 
        iamroleurl=https://s3.amazonaws.com/mycicd-bucket-ap3/cicd-files/iam_roles.yaml
        bucketurl=https://s3.amazonaws.com/mycicd-bucket-ap3/cicd-files/bucket.yaml
        dbresourcelinkurl=https://s3.amazonaws.com/mycicd-bucket-ap3/cicd-files/glue_resourcelink.yaml
        lfpermissionsurl=https://s3.amazonaws.com/mycicd-bucket-ap3/cicd-files/lfpermissions.yaml   
        lfurl=https://s3.amazonaws.com/mycicd-bucket-ap3/cicd-files/lakeformation.yaml                 
        aws cloudformation deploy \
          --template-file $cfnfile \
          --stack-name datamesh-stack \
          --parameter-overrides EnvType="${env}" DomainName="${domain}" IAMRolePath="${iamroleurl}" BucketFilePath="${bucketurl}" ResourcelinkPath="${dbresourcelinkurl}" lfPath="${lfurl}" lfpermissionsPath="${lfpermissionsurl}"\
          --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM
  post_build:
    commands:
      - aws cloudformation describe-stack-events --stack-name datamesh-stack
      - echo Build complete